// TODO: Create a function that returns a license badge based on which license is passed in
// If there is no license, return an empty string
function renderLicenseBadge(license) {
  if (license !== "None") {
    return `![Badge](https://img.shields.io/badge/License-${license}-blue.svg)`
  }
  return ``;
}

// TODO: Create a function that returns the license link
// If there is no license, return an empty string
function renderLicenseLink(license) {
  if (license !== "None") {
    return `- [License](#license)`
  }
  return ``;
}

// TODO: Create a function that returns the license section of README
// If there is no license, return an empty string
function renderLicenseSection(license) {
  if (license !== "None") {
    return `## License
    This application is covered by the ${license} license.`
  }
  return ``;

}

// TODO: Create a function to generate markdown for README
function generateMarkdown(data) {
  return `
#  ${data.title}
  ${renderLicenseBadge(data.license)}

## Description
${data.description}

## Table of Contents (Optional)
${data.content}
- [Installation](#installation)
- [Usage](#usage)
- [Credits](#credits)
- [License](#license)
- [Badge](#badge)
- [Features](#features)
- [Contributing](#contributing)
- [Tests](#tests)
- [Questions](questions)

## Installation
${data.installation}

## Usage
${data.usage}

## Demo
${data.demo}

## Credits
${data.credits}

${renderLicenseSection(data.license)}

---
## Badges
${renderLicenseBadge(data.license)}
![badmath](https://img.shields.io/github/languages/top/lernantino/badmath)

## Features
${data.features}

## Contributing
${data.contribute}

## Tests
${data.tests}

## Questions
${data.questions}
If you have any question, Email me at: ${data.email} 

Find me on GitHub: [${data.username}](https://github.com/${data.username})   

---
_This README was generated by [Readme.md](https://github.com/B-smd/Professional-README-Generator) © 2022_

`;
}

module.exports = generateMarkdown;
